In [3]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.10.tar.gz (385 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.10-cp312-cp312-macosx_10_15_x86_64.whl size=134610 sha256=77d1698ea973a0e0d22de1f83390661cc83016355584e0c1316283db23a37177
  Stored in directory: /Users/mac/Library/Caches/pip/wheels/ac/bb/ce/afa589c50b6004d3a06fc691e71bd09c9bd5f01e5921e5329b
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10

In [4]:
from sqlalchemy import create_engine
import pandas as pd

In [7]:
# Step 3: Connect to PostgreSQL Database
POSTGRES_USER = "postgres"  # Change to your PostgreSQL username
POSTGRES_PASSWORD = "12345678"  # Change to your PostgreSQL password
POSTGRES_HOST = "localhost"  # Change if running remotely
POSTGRES_PORT = "5432"  # Default PostgreSQL port
POSTGRES_DB = "altschool_db"  # Change to your PostgreSQL database name

DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# Create SQLAlchemy engine
engine = create_engine(DATABASE_URL)

# Step 4: Save Data to PostgreSQL
TABLE_NAME = "public.flights"

# Step 5: Query & Verify Data
query_result = pd.read_sql(f"SELECT * FROM {TABLE_NAME} LIMIT 5;", con=engine)
query_result

,id,airline_name,airline_code,flight_number,origin_airport,origin_city,origin_state,destination_airport,destination_city,destination_state,...,air_traffic_delay,arrival_delay,carrier_delay,departure_delay,late_aircraft_delay,security_delay,weather_delay,wheels_off_time,wheels_on_time,day_of_week
0,1,Delta Air Lines Inc.,DL,2454,SNA,Santa Ana,California,ATL,Atlanta,Georgia,...,0,-17,0,10,0,0,0,714,1334,Thursday
1,2,Delta Air Lines Inc.,DL,2455,AUS,Austin,Texas,ATL,Atlanta,Georgia,...,0,-17,0,-4,0,0,0,708,945,Thursday
2,3,Delta Air Lines Inc.,DL,2456,JFK,New York,New York,FLL,Fort Lauderdale,Florida,...,0,-20,0,-4,0,0,0,1154,1426,Thursday
3,4,Delta Air Lines Inc.,DL,2457,ATL,Atlanta,Georgia,BDL,Hartford,Connecticut,...,0,3,0,-3,0,0,0,753,941,Thursday
4,5,Delta Air Lines Inc.,DL,2457,BDL,Hartford,Connecticut,ATL,Atlanta,Georgia,...,0,-25,0,-5,0,0,0,1042,1254,Thursday