In [7]:
import pandas as pd
import requests 
from io import StringIO
from sqlalchemy import create_engine
from csv_module import csv_downloader, send_data_to_db
import csv_module

In [ ]:
csv_module.csv_downloader()

In [5]:
CSV_URL = "https://drive.usercontent.google.com/u/0/uc?id=1TQRSONybodmFG7yBrMuCxb2JRFVaowJR&export=download"

flights = csv_downloader(csv_url=CSV_URL)

In [6]:
flights.head()

,actual_arrival_time,actual_flight_time,actual_departure_time,air_time,air_traffic_delay,airline_code,airline_name,arrival_delay,cancellation_reason,carrier_delay,...,origin_state,scheduled_arrival_time,scheduled_departure_time,scheduled_flight_time,security_delay,was_cancelled,weather_delay,wheels_off_time,wheels_on_time,day_of_week
0,1339.0,224.0,655.0,200.0,0,DL,Delta Air Lines Inc.,-17.0,NaN,0,...,California,1356,645,251,0,False,0,714.0,1334.0,Thursday
1,951.0,115.0,656.0,97.0,0,DL,Delta Air Lines Inc.,-17.0,NaN,0,...,Texas,1008,700,128,0,False,0,708.0,945.0,Thursday
2,1429.0,180.0,1129.0,152.0,0,DL,Delta Air Lines Inc.,-20.0,NaN,0,...,New York,1449,1133,196,0,False,0,1154.0,1426.0,Thursday
3,944.0,140.0,724.0,108.0,0,DL,Delta Air Lines Inc.,3.0,NaN,0,...,Georgia,941,727,134,0,False,0,753.0,941.0,Thursday
4,1300.0,146.0,1034.0,132.0,0,DL,Delta Air Lines Inc.,-25.0,NaN,0,...,Connecticut,1325,1039,166,0,False,0,1042.0,1254.0,Thursday

In [ ]:
database = 'flights_db'
table = 'aero_flights'

send_data_to_db(df=flights, db_name=database, table_name=table)